# Load this file when using docker-compose in testing via the -f flag.
version: "3.7"
services:
  web:
    image: derbyevan/majestic-app_web:latest
    env_file: ./config/.web.env
    restart: on-failure
    depends_on:
      - db
    ports:
      - "80:8000"
  db:
    image: derbyevan/majestic-app_db:latest
    env_file: ./config/.db.env
    restart: on-failure
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    expose:
      - "7654"
volumes:
  dbdata:
