# This file outlines basic settings when using docker-compose with this codebase.
version: "3.7"
services:
  web:
    build: .
    env_file: ./config/.web.env
    depends_on:
        - db
  db:
    build: ./db/ 
    env_file: ./config/.db.env
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "7654"
volumes:
  dbdata: