# Load this file when using docker-compose in production via the -f flag.
version: "3.7"
services:
  web:
    image: derbyevan/majestic-app_web:latest
    ports:
      - "80:8000"
  db:
    image: derbyevan/majestic-app_db:latest