# Load this file when using docker-compose in production via the -f flag.
version: "3.7"
services:
  web:
    image: derbyevan/majestic-app_web:stable
    env_file: ./config/.web.env
    # environment:
      # HTTPS disabled until cert can be acquired
      # - SERVE_HTTPS=1
    restart: on-failure
    depends_on:
      - db
    ports:
      - "80:8000"
      - "443:8443"
  db:
    image: derbyevan/majestic-app_db:stable
    env_file: ./config/.db.env
    restart: on-failure
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "7654"
volumes:
  dbdata: