# This file is automatically loaded when docker-compose is used without the -f flag.
# It acts as a development configuration for the docker-compose environment with this app.
# When the app is deployed in production, this compose file should explicitly not be used.
version: "3.7"
services:
  web:
    command: npm run docker-node-dev
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
    ports:
      - "8000:8000"
  db:
    ports:
      - "7654:7654"
